version: '3.8'

services:
  kafka-fleet:
    image: apache/kafka:latest
    hostname: kafka
    container_name: kafka-fleet
    ports:
      - "19092:9092"
    environment:
        KAFKA_NODE_ID: 0
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_LISTENERS: PLAINTEXT://kafka-fleet:9092,CONTROLLER://kafka-fleet:9093
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-fleet:9092
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka-fleet:9093
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_NUM_PARTITIONS: 1
        KAFKA_CLUSTER_ID: kafka-fleet
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-fleet:9092 --list"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kafka-fleet-network

  kafka-2:
    image: apache/kafka:latest
    hostname: kafka-2
    container_name: kafka-2
    ports:
      - "29092:9092"
    environment:
        KAFKA_NODE_ID: 0
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_LISTENERS: PLAINTEXT://kafka-2:9092,CONTROLLER://kafka-2:9093
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka-2:9093
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_NUM_PARTITIONS: 1
        KAFKA_CLUSTER_ID: kafka-2
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-2:9092 --list"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kafka-2-network
    
  kafka-3:
    image: apache/kafka:latest
    hostname: kafka-3
    container_name: kafka-3
    ports:
      - "39092:9092"
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka-3:9092,CONTROLLER://kafka-3:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_CLUSTER_ID: kafka-3
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-3:9092 --list"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kafka-3-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    hostname: kafka-ui
    depends_on:
      kafka-fleet:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka-fleet
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-fleet:9092
      KAFKA_CLUSTERS_1_NAME: kafka-2
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: kafka-2:9092
      KAFKA_CLUSTERS_2_NAME: kafka-3
      KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS: kafka-3:9092
    networks:
      - kafka-fleet-network
      - kafka-2-network
      - kafka-3-network

networks:
  kafka-fleet-network:
    driver: bridge
  kafka-2-network:
    driver: bridge
  kafka-3-network:
    driver: bridge

